steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/my-cloud-run-service:${SHORT_SHA}"
      - "."
  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "my-cloud-run-service"  # Name of the Cloud Run service
      - "--image"
      - "gcr.io/${PROJECT_ID}/my-cloud-run-service:${SHORT_SHA}"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"  # Specify your region
      - "--allow-unauthenticated"  # Optional, depends on whether you want public access
images:
  - "gcr.io/${PROJECT_ID}/my-cloud-run-service:${SHORT_SHA}"
